#!/bin/bash
if test $# -lt 1
then
echo Usage: $0 start | stop | restart | status | debug | enable | disable
else
case "$1" in
status)
	if test -e /var/run/NVDARemoteServer.pid
	then
		echo NVDARemoteServer is running
	else
		echo NVDARemoteServer is stopped
	fi
	;;
*)
	python /usr/share/NVDARemoteServer/server.py $1
	;;
esac
fi
