services:
  nvdaremoteserver:
    container_name: nvdaremoteserver
    image: jmdaweb/nvda-remote-server:latest
    restart: always
    volumes:
      - ./data:/data
    network_mode: host
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
