#!/bin/bash
cd /usr/share/NVDARemoteServer
openssl genpkey -out key.key -algorithm EC -pkeyopt ec_paramgen_curve:secp384r1
openssl req -new -key key.key -out cert.csr -sha512
openssl x509 -req -days 3650 -in cert.csr -signkey key.key -out cert.crt
rm -f server.pem
mv key.key server.pem
cat cert.crt >> server.pem
rm -f cert.csr cert.crt
chmod 644 server.pem
echo Certificate successfully created.
echo You should restart the server for the changes to take effect on all connected clients.
exit