#!/bin/bash

# Comments to support chkconfig on RedHat Linux
# chkconfig: - 64 36
# description: a relay server for NVDA Remote

### BEGIN INIT INFO
# Provides:          NVDARemoteServer
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     
# Default-Stop:      
# Short-Description: Start/stop NVDARemote server
# Description:       a relay server for NVDA Remote
### END INIT INFO

# Location of NVDARemote server binary
BIN="/usr/bin/python3 /usr/share/NVDARemoteServer/server.py"
# The NVDARemote server should be launched by this user account
USER=nvdaremoteserver
# Location of NVDARemote server pidfile
PIDDIRECTORY=/var/run/NVDARemoteServer
if ! test -e $PIDDIRECTORY
then
mkdir $PIDDIRECTORY
chown $USER:$USER $PIDDIRECTORY
chmod 755 $PIDDIRECTORY
fi
PIDFILE=/var/run/NVDARemoteServer/NVDARemoteServer.pid

if test -e /lib/lsb/init-functions
then
	. /lib/lsb/init-functions
fi

# Carry out specific functions when asked to by the system
case "$1" in
    start)
	su $USER -c "$BIN start" -s /bin/sh
	touch /var/lock/subsys/nvdaremoteserver
	exit $?
	;;
    stop)
	su $USER -c "$BIN stop " -s /bin/sh
	rm -f /var/lock/subsys/nvdaremoteserver
	exit $?
	;;
    restart)
	$0 stop || exit $?
	$0 start || exit $?
	;;
reload)
	$0 restart || exit $?
	;;
force-reload)
	$0 reload || exit $?
	;;
status)
	if test -e $PIDFILE
	then
		echo NVDARemoteServer is running
	else
		echo NVDARemoteServer is stopped
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
