#!/bin/bash
# Post installation script.
 # This script runs after installing the package 

set -e
systemctl daemon-reload
systemd-tmpfiles --create
NVDARemoteServer enable
NVDARemoteServer start
set +e
exit 0