#!/bin/bash
# Post removal script.
 # This script runs after removing the package 

set -e
if test $1 = remove
then
if test -e /usr/share/NVDARemoteServer
then
rm -rf /usr/share/NVDARemoteServer
fi
fi
if test $1 = purge
then
if test -e /var/log/NVDARemoteServer.log
then
rm -f /var/log/NVDARemoteServer.log
fi
userdel nvdaremoteserver
fi
systemctl daemon-reload
set +e
exit 0
