#!/bin/bash
# Post removal script.
 # This script runs after removing the package 

set -e
if test -e /usr/share/NVDARemoteServer
then
rm -rf /usr/share/NVDARemoteServer
fi
update-rc.d NVDARemoteServer remove
set +e
exit 0
