#!/bin/bash
if test $# -lt 1
then
echo "Usage: $0 start | stop | restart | status | debug | enable | disable | kill"
else
case "$1" in
start | stop | restart | status)
	service nvdaremoteserver $1
	;;
enable)
	chkconfig nvdaremoteserver on
	;;
disable)
	chkconfig nvdaremoteserver off
	;;
*)
	python /usr/share/NVDARemoteServer/server.py $*
	;;
esac
fi
