#!/bin/bash
# Post installation script.
 # This script runs after installing the package 

set -e
if ! test -e /var/log/NVDARemoteServer
then
mkdir /var/log/NVDARemoteServer
fi
chown -R nvdaremoteserver:nvdaremoteserver /var/log/NVDARemoteServer
update-rc.d NVDARemoteServer defaults
NVDARemoteServer enable
NVDARemoteServer start
set +e
exit 0