.\" Manpage for NVDARemoteServer.conf
.\" Contact jm.delicado@nvda.es to correct errors or typos.
.TH man 5 "01 Sep 2018" "1.7" "NVDARemoteServer.conf man page"
.SH NAME
NVDARemoteServer.conf \- Change NVDARemoteServer configuration
.SH DESCRIPTION
.P
NVDARemoteServer.conf is the configuration file for NVDARemoteServer. On most Unix systems, it is located under /etc directory. This file has the following specifications:
.P
Blank lines are allowed. The server will ignore them.
.P
Lines starting with a # character are comments, and the server ignore them. At the moment, a comment in the same line as a setting is not allowed.
.P
Each setting goes in a line, and has the following format: option=value
.P
Spaces between option and value, before option and after value are not allowed. The server will fail and switch to default settings if it can't parse the configuration.
.P
The file has unix-style line breaks, and is encoded in UTF\-8.
.P
All options are lowercase.
.SH OPTIONS
.P
The following options are available. You can uncomment them in the file or add new lines.
.P
interface
.P
Set the ip address of the interface where the server will listen for new incoming connections. By default it listens on all available interfaces (address 0.0.0.0). In some platforms, interface setting will not work if interface6 is not configured to bind to a specific address.
.P
Example: interface=127.0.0.1
.P
interface6
.P
Set the IPV6 address of the interface where the server will listen for new incoming connections. By default it listens on all available interfaces (address ::).
.P
Example: interface6=::1
.P
port
.P
Set the server tcp port. By default it is 6837.
.P
Example: port=6838
.P
port6
.P
Listen on the specified port, but only for IPV6. By default, use the value specified in port. Use this value if you want different ports for IPV4 and IPV6 sockets.
.P
Example: port6=6838
.P
logfile
.P
Set the path of the server log file. On Unix systems, the default path is /var/log/NVDARemoteServer.log. On Windows, it's the same path as the server executable.
.P
Example: logfile=/home/john/logs/NVDARemoteServer.log
.P
pidfile
.P
When the server is running, the process id is stored in a file. Here you can set the path for that file. By default it's /var/run/NVDARemoteServer.pid
.P
Example: pidfile=/home/john/run/NVDARemoteServer.pid
.P
loglevel
.P
Set the information that the server will write to the log. You must enter a value between 0 and 3. 0 means only errors and warnings, 1 adds connection info, 2 is used for debugging purposes and 3 prints also the channel passwords.
.P
Warning! Although level 3 is set by default, you must change it to give less information, as level 3 is a security risk specially in production environments.
.P
Example: loglevel=2
.P
pemfile
.P
This setting specifies the path to a pem-encoded, concatenated private key and certificate for ssl connections.
.P
The pem file must contain firstly the private key without passphrase encryption, followed by an unix-style line ending and the certificate. Additional ca and root certificates can be added below this content.
.P
By default, use server.pem located in the same path as server.py.
.P
Example: pemfile=/etc/apache2/ssl/certificate.pem
.P
motd
.P
This is the message displayed to all clients which join a channel. If you collect user data, this is a good place to specify an URL to your privacy policy, if available. The message must be written in a single line. Multiline support is not available yet. By default no message is displayed.
.P
Example: motd=Hello, welcome to my relay server
.P
motd_force_display
.P
The message of the day can be displayed once (only for first-time clients) or each time a client joins a channel. Possible values for this setting: 0=False, other integer values mean True. Defaults to False (do not force display).
.P
Example: motd_force_display=1
.SH SEE ALSO
NVDARemoteServer (1), NVDARemoteCertificate (1)
.SH BUGS
Report bugs to jm.delicado@nvda.es
.SH AUTHOR
Jose Manuel Delicado (jm.delicado@nvda.es)