.\" Manpage for NVDARemoteUninstall.
.\" Contact jm.delicado@nvda.es to correct errors or typos.
.TH man 1 "19 Dec 2021" "2.1" "NVDARemoteUninstall man page"
.SH NAME
NVDARemoteUninstall \- Uninstall easily NVDA Remote Server
.SH SYNOPSIS
NVDARemoteUninstall
.SH DESCRIPTION
NVDARemoteUninstall will stop and remove NVDA Remote Server on Cygwin and Mac Os x, where package managers don't work as expected.
.P
Warning! If you run the script, the server will be fully removed without warnings and prompts.
.SH OPTIONS
No options are required.
.SH SEE ALSO
NVDARemoteServer (1), NVDARemoteServer.conf (5), NVDARemoteCertificate (1)
.SH BUGS
Report bugs to jm.delicado@nvda.es
.SH AUTHOR
Jose Manuel Delicado (jm.delicado@nvda.es)