.\" Manpage for NVDARemoteServer.
.\" Contact info@technow.es to correct errors or typos.
.TH man 1 "12 Jul 2015" "1.0" "NVDARemoteServer man page"
.SH NAME
NVDARemoteServer \- Manage quickly the NVDA Remote Server
.SH SYNOPSIS
NVDARemoteServer [start|stop|restart|status|enable|disable]
.SH DESCRIPTION
NVDARemoteServer is a script to control the NVDA Remote Server in an easy way. You can start, stop, restart, manage and view the status of the service.
.SH OPTIONS
Start: starts the service, or throws an error if the service is already started.
Stop: stops the service.
Restart: restarts the service.
Status: gives information about the service.
Enable: configures the service to run at system startup.
Disable: configures the service to be started manually.
.SH BUGS
Report bugs to info@technow.es
.SH AUTHOR
Technow (info@technow.es)