.\" Manpage for NVDARemoteCertificate.
.\" Contact jmdaweb@hotmail.com to correct errors or typos.
.TH man 1 "14 Jan 2017" "1.4" "NVDARemoteCertificate man page"
.SH NAME
NVDARemoteCertificate \- Generate a certificate for NVDA Remote Server
.SH SYNOPSIS
NVDARemoteCertificate
.SH DESCRIPTION
NVDARemoteCertificate is a script to generate a ssl certificate for your server. It is highly recommended that you run this script before starting the server for the first time. It will replace the default certificate and enhance security.
.SH OPTIONS
No options are required.
.SH BUGS
Report bugs to jmdaweb@hotmail.com
.SH AUTHOR
Jose Manuel Delicado (jmdaweb@hotmail.com)