.\" Manpage for NVDARemoteCertificate.
.\" Contact jmdaweb@hotmail.com to correct errors or typos.
.TH man 1 "09 Sep 2017" "1.5" "NVDARemoteCertificate man page"
.SH NAME
NVDARemoteCertificate \- Generate a certificate for NVDA Remote Server
.SH SYNOPSIS
NVDARemoteCertificate
.SH DESCRIPTION
NVDARemoteCertificate is a script to generate a ssl certificate for your server. It is highly recommended that you run this script before starting the server for the first time. It will replace the default certificate and enhance security.
.P
Once started, you will be prompted to enter some information for your certificate (organization, name, e-mail, country code, ...).
After that, a self-signed certificate will be generated and stored with a private key into the server.pem file. On Unix systems, you will find this file at /usr/share/NVDARemoteServer/server.pem. On Windows, this file is in the same location as the server executable.
.SH OPTIONS
No options are required.
.SH SEE ALSO
NVDARemoteServer (1), NVDARemoteServer.conf (5)
.SH BUGS
Report bugs to jmdaweb@hotmail.com
.SH AUTHOR
Jose Manuel Delicado (jmdaweb@hotmail.com)