.\" Manpage for NVDARemoteServer.
.\" Contact jmdaweb@hotmail.com to correct errors or typos.
.TH man 1 "19 Jul 2017" "1.4.2" "NVDARemoteServer man page"
.SH NAME
NVDARemoteServer \- Manage quickly the NVDA Remote Server
.SH SYNOPSIS
NVDARemoteServer [start|stop|restart|status|enable|disable|debug|kill]
.SH DESCRIPTION
NVDARemoteServer is a script to control the NVDA Remote Server in an easy way. You can start, stop, restart, manage and view the status of the service.
.SH OPTIONS
Start: starts the service, or throws an error if the service is already started.
Stop: stops the service.
Restart: restarts the service.
Status: gives information about the service.
Enable: configures the service to run at system startup.
Disable: configures the service to be started manually.
Debug: starts the server in debug mode. You can see the server activity in the console. To stop the server, press ctrl+c
Kill: sometimes the server gets completely frozen in some systems. Use this command to kill the process.
.SH BUGS
Report bugs to jmdaweb@hotmail.com
.SH AUTHOR
Jose Manuel Delicado (jmdaweb@hotmail.com)