#!/bin/bash
### BEGIN INIT INFO
# Provides:          NVDARemoteServer
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop NVDARemote server
# Description:       Setup variables BIN and USER
#                    before running this script
### END INIT INFO

# Location of NVDARemote server binary
BIN="/usr/bin/python /usr/share/NVDARemoteServer/server.py"
# The NVDARemote server should be launched by this user account
USER=nvdaremoteserver
PIDDIRECTORY=/var/run/NVDARemoteServer
if ! test -e $PIDDIRECTORY
then
mkdir $PIDDIRECTORY
chown $USER:$USER $PIDDIRECTORY
chmod 755 $PIDDIRECTORY
fi
# Location of NVDARemote server pidfile
PIDFILE=/var/run/NVDARemoteServer/NVDARemoteServer.pid

. /lib/lsb/init-functions

# Carry out specific functions when asked to by the system
case "$1" in
    start)
	su $USER -c "$BIN start" -s /bin/sh
	;;
    stop)
	su $USER -c "$BIN stop" -s /bin/sh
	;;
    restart)
	$0 stop || exit 1
	$0 start || exit 1
	;;
status)
	if test -e $PIDFILE
	then
		echo NVDARemoteServer is running
	else
		echo NVDARemoteServer is stopped
	fi
	;;
    *)
	echo "Usage: $0 {start|stop|restart|status|force-reload}"
	exit 1
	;;
esac

exit 0
