#!/bin/bash
# Pre installation script.
 # This script runs before installing the package 

set -e
if ! getent group nvdaremoteserver > /dev/null
then
addgroup --system nvdaremoteserver >/dev/null
fi
if ! getent passwd nvdaremoteserver > /dev/null
then
adduser --system --disabled-login --ingroup nvdaremoteserver --no-create-home --home /nonexistent --gecos "NVDA remote server" --shell /bin/false nvdaremoteserver > /dev/null
fi
set +e
exit 0