#!/bin/bash
# Post installation script.
 # This script runs after installing the package 

set -e
if ! test -e /var/log/NVDARemoteServer.log
then
touch /var/log/NVDARemoteServer.log
chown nvdaremoteserver:nvdaremoteserver /var/log/nvdaremoteserver.log
fi
update-rc.d NVDARemoteServer defaults
service NVDARemoteServer start
set +e
exit 0